#!/bin/bash
set -euo pipefail

COPYRIGHT="Copyright (c) 2022 Cyber Home Lab authors"
DEBUG_MSG="$(tput setaf 6)DEBUG  : \t$(tput sgr0)"
INFO_MSG="$(tput setaf 2)INFO   : \t$(tput sgr0)"
WARNING_MSG="$(tput setaf 3)WARNING: \t$(tput sgr0)"
ERROR_MSG="$(tput setaf 1)ERROR  : \t$(tput sgr0)"

# Prerequisites
rm -f /tmp/pre-push.err /tmp/pre-push.log
if (
    git --version
    golangci-lint version
    git pull
    go fmt
    go get
    go mod tidy
) 2>/tmp/pre-push.err >/tmp/pre-push.log
then
    echo -e "${INFO_MSG}Prerequistes run successfully"
else
    echo -e "${ERROR_MSG}Issues in running prerequistes\n * For more info, run -> make check-pre-push\n"
    exit 2
fi

# Linting
if (
    golangci-lint run
) 2>/tmp/pre-push.err >/tmp/pre-push.log
then
    echo -e "${INFO_MSG}Linting run successfully"
else
    echo -e "${ERROR_MSG}Issues in the linting process\n * For more info, run -> make check-pre-push\n"
    exit 2
fi

# Tests
if (
    go test -v ./...
) 2>/tmp/pre-push.err >/tmp/pre-push.log
then
    echo -e "${INFO_MSG}Go tests run successfully"
else
    echo -e "${ERROR_MSG}Issues in the go test\n * For more info, run -> make check-pre-push\n"
    exit 2
fi

# Benchmark
if (
    go test -run=XXX -bench=.
) 2>/tmp/pre-push.err >/tmp/pre-push.log
then
    echo -e "${INFO_MSG}Go benchmarks run successfully"
else
    echo -e "${ERROR_MSG}Issues in the go benchmarks\n * For more info, run -> make check-pre-push\n"
    exit 2
fi

# Coverage
go test -cover ./... -coverprofile=coverage.out >/dev/null
if go tool cover -func=coverage.out | grep -qvE '^total:|init|(7|8|9|10)[0-9].[0-9]%$'
then
    echo -e "${ERROR_MSG}Coverage is under 70%\n * For more info, run -> make check-coverage\n"
    exit 2
else
    echo -e "${INFO_MSG}Coverage is more than 70%"
fi

# TODOs
todos="$(find . -type f -name "*.go" | xargs cat | grep -c TODO)"
if [[ "${todos}" == "0" ]]
then
    echo -e "${INFO_MSG}0 TODOs"
else
    echo -e "${WARNING_MSG}${todos} TODOs\n * For more info, run -> make check-todos"
fi

# Copyright
for file in $(find . -type f -name "*.go")
do
    if head -3 "${file}" | tail -1 | grep -v "${COPYRIGHT}"
    then
        echo -e "${ERROR_MSG}Copyright missing from file ${file}\n * For more info, run -> make check-copyright\n"
        exit 2
    fi
done
echo -e "${INFO_MSG}Copyright set for all Go files"
